### ISSUE TITLE
Application crash when game finished

### ISSUE THREAD

**Issue by sid4fun** [udacity/andfun-kotlin-guess-it#21]
Hi Team, 
the steps are as follows to reproduce the issue,
1) on finishing all the words, just before pressing GOT IT, change the orientation.
2) once the orientation is changed, now press GOT IT button .
3) There is application crash with below logs.
2020-12-30 09:07:14.599 4328-4328/com.example.android.guesstheword E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.guesstheword, PID: 4328
    java.lang.IllegalStateException: no current navigation node
        at androidx.navigation.NavController.navigate(NavController.java:765)
        at androidx.navigation.NavController.navigate(NavController.java:745)
        at androidx.navigation.NavController.navigate(NavController.java:731)
        at androidx.navigation.NavController.navigate(NavController.java:863)
        at com.example.android.guesstheword.screens.game.GameFragment.gameFinished(GameFragment.kt:87)
        at com.example.android.guesstheword.screens.game.GameFragment.access$gameFinished(GameFragment.kt:35)
        at com.example.android.guesstheword.screens.game.GameFragment$onCreateView$3.onChanged(GameFragment.kt:65)
        at com.example.android.guesstheword.screens.game.GameFragment$onCreateView$3.onChanged(GameFragment.kt:35)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.example.android.guesstheword.screens.game.GameViewModel.nextWord(GameViewModel.kt:90)
        at com.example.android.guesstheword.screens.game.GameViewModel.onCorrect(GameViewModel.kt:105)
        at com.example.android.guesstheword.screens.game.GameFragment$onCreateView$4.onClick(GameFragment.kt:71)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by sid4fun** [comment]
Replacing 
implementation "android.arch.navigation:navigation-fragment-ktx:1.0.0-rc02"
    implementation "android.arch.navigation:navigation-ui-ktx:1.0.0-rc02"
with
    implementation "androidx.navigation:navigation-fragment-ktx:2.3.0-alpha04"
    implementation "androidx.navigation:navigation-ui-ktx:2.3.0-alpha04"

worked fine.
